// src/components/PageNav.tsx
"use client";

import Link from "next/link";
import type { DocEntry } from "@/lib/docs";

interface PageNavProps {
  prev: DocEntry | null;
  next: DocEntry | null;
}

export function PageNav({ prev, next }: PageNavProps) {
  return (
    <nav className="flex justify-between mt-12 pt-6 border-t border-gray-100 gap-4">
      {prev ? (
        <Link
          href={`/docs/${prev.slug}`}
          className="flex flex-col p-3 border border-gray-200 rounded-lg no-underline transition-all hover:border-indigo-200 hover:bg-indigo-50/30 flex-1 min-w-0"
        >
          <span className="text-[0.65rem] font-semibold uppercase tracking-wider text-gray-400 mb-1">
            ← Previous
          </span>
          <span className="text-sm font-medium text-indigo-600 truncate">
            {prev.title}
          </span>
        </Link>
      ) : (
        <span />
      )}
      {next ? (
        <Link
          href={`/docs/${next.slug}`}
          className="flex flex-col p-3 border border-gray-200 rounded-lg no-underline transition-all hover:border-indigo-200 hover:bg-indigo-50/30 flex-1 min-w-0 text-right"
        >
          <span className="text-[0.65rem] font-semibold uppercase tracking-wider text-gray-400 mb-1">
            Next →
          </span>
          <span className="text-sm font-medium text-indigo-600 truncate">
            {next.title}
          </span>
        </Link>
      ) : (
        <span />
      )}
    </nav>
  );
}

// src/lib/components/PageNav.svelte
<script lang="ts">
  import { resolveRoute } from "$app/paths";
  import { goto } from "$app/navigation";
  import { getAdjacentDocs } from "$lib/docs";
  import { onMount } from "svelte";

  let { slug }: { slug: string } = $props();
  let adjacent = $derived(getAdjacentDocs(slug));

  onMount(() => {
    function onKeydown(e: KeyboardEvent) {
      if (e.altKey && e.key === "ArrowLeft" && adjacent.prev) {
        e.preventDefault();
        goto(`/docs/${adjacent.prev.slug}`);
      }
      if (e.altKey && e.key === "ArrowRight" && adjacent.next) {
        e.preventDefault();
        goto(`/docs/${adjacent.next.slug}`);
      }
    }
    document.addEventListener("keydown", onKeydown);
    return () => document.removeEventListener("keydown", onKeydown);
  });
</script>

{#if adjacent.prev || adjacent.next}
  <nav
    class="grid grid-cols-2 gap-4 mt-12 pt-6 border-t border-gray-200"
    aria-label="Page navigation"
  >
    {#if adjacent.prev}
      <a
        href={resolveRoute("/docs/[slug]", { slug: adjacent.prev.slug })}
        class="group flex flex-col gap-1 p-4 rounded-lg border border-gray-200 hover:border-indigo-200 hover:bg-indigo-50/50 transition-all"
      >
        <span
          class="text-[0.65rem] uppercase tracking-wider text-gray-400 group-hover:text-indigo-400"
          >← Previous</span
        >
        <span
          class="text-sm font-medium text-gray-700 group-hover:text-indigo-600"
          >{adjacent.prev.title}</span
        >
      </a>
    {:else}
      <div></div>
    {/if}

    {#if adjacent.next}
      <a
        href={resolveRoute("/docs/[slug]", { slug: adjacent.next.slug })}
        class="group flex flex-col items-end gap-1 p-4 rounded-lg border border-gray-200 hover:border-indigo-200 hover:bg-indigo-50/50 transition-all"
      >
        <span
          class="text-[0.65rem] uppercase tracking-wider text-gray-400 group-hover:text-indigo-400"
          >Next →</span
        >
        <span
          class="text-sm font-medium text-gray-700 group-hover:text-indigo-600"
          >{adjacent.next.title}</span
        >
      </a>
    {:else}
      <div></div>
    {/if}
  </nav>
{/if}
