// src/components/TableOfContents.tsx
"use client";

import { useEffect, useState } from "react";

interface TocItem {
  id: string;
  text: string;
}

export function TableOfContents() {
  const [headings, setHeadings] = useState<TocItem[]>([]);
  const [activeId, setActiveId] = useState("");

  useEffect(() => {
    const article = document.getElementById("doc-content");
    if (!article) return;

    const h2s = article.querySelectorAll("h2");
    const items: TocItem[] = [];
    h2s.forEach((h, i) => {
      const id = h.id || `section-${i}`;
      if (!h.id) h.id = id;
      items.push({ id, text: h.textContent || "" });
    });
    setHeadings(items);

    const observer = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            setActiveId(entry.target.id);
          }
        }
      },
      { rootMargin: "-10% 0px -80% 0px", threshold: 0 }
    );

    h2s.forEach((h) => observer.observe(h));
    return () => observer.disconnect();
  }, []);

  if (headings.length === 0) return null;

  return (
    <div className="sticky top-12">
      <div className="text-[0.65rem] font-semibold text-gray-400 uppercase tracking-widest mb-3">
        On this page
      </div>
      <nav className="space-y-0.5 border-l border-gray-100 pl-3">
        {headings.map((h) => (
          <a
            key={h.id}
            href={`#${h.id}`}
            onClick={(e) => {
              e.preventDefault();
              document
                .getElementById(h.id)
                ?.scrollIntoView({ behavior: "smooth", block: "start" });
            }}
            className={`block py-1 text-xs transition-colors ${
              activeId === h.id
                ? "text-indigo-600 font-medium"
                : "text-gray-400 hover:text-gray-600"
            }`}
          >
            {h.text}
          </a>
        ))}
      </nav>
    </div>
  );
}

// src/lib/components/TableOfContents.svelte
<script lang="ts">
  import { onMount } from "svelte";

  let {
    headings,
  }: { headings: { id: string; text: string; depth: number }[] } = $props();
  let activeId = $state("");

  onMount(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            activeId = entry.target.id;
          }
        }
      },
      { rootMargin: "-80px 0px -70% 0px", threshold: 0 },
    );

    for (const h of headings) {
      const el = document.getElementById(h.id);
      if (el) observer.observe(el);
    }

    return () => observer.disconnect();
  });
</script>

{#if headings.length > 0}
  <nav class="toc hidden xl:block w-56 shrink-0">
    <div class="sticky top-20 max-h-[calc(100vh-6rem)] overflow-y-auto">
      <div
        class="text-[0.65rem] font-semibold text-gray-400 uppercase tracking-widest mb-2"
      >
        On this page
      </div>
      <ul class="space-y-0.5 border-l border-gray-100">
        {#each headings as heading (heading.id)}
          <li
            style="padding-left: {(heading.depth - 2) * 0.75 + 0.75}rem"
            class="-ml-px border-l-2 transition-colors {activeId === heading.id
              ? 'border-indigo-500'
              : 'border-transparent'}"
          >
            <a
              href={`#${heading.id}`}
              class="block text-[0.75rem] py-1 transition-colors {activeId ===
              heading.id
                ? 'text-indigo-600 font-medium'
                : 'text-gray-400 hover:text-gray-600'}"
            >
              {heading.text}
            </a>
          </li>
        {/each}
      </ul>
    </div>
  </nav>
{/if}
